### ISSUE TITLE
Preserve image tags

### ISSUE THREAD

**Issue by ghost** [lautr3k/lw.svg-parser#1]
Just to keep trace of this request https://github.com/LaserWeb/LaserWeb4/issues/58#issuecomment-268070837

**Comment by ghost** [comment]
@tbfleming Just added `<image>` and `<text>` tags, module up-to-date. 
(`<text>` string can be reached from `tag.element.textContent`.)

**Comment by tbfleming** [comment]
Last I checked, browsers didn't provide a way to extract vector data from fonts. Did Chrome add this ability recently?

**Comment by ghost** [comment]
I do not know, but we could give a set of defaults fonts and the option to upload others. Better than no support for texts?

**Comment by ghost** [comment]
Somthing like used in THREE http://gero3.github.io/facetype.js/
