### ISSUE TITLE
SVG is not opened properly

### ISSUE THREAD

**Issue by gndprx** [lautr3k/lw.svg-parser#2]
When opening the attached SVG, the paths seem to open at random locations rather than adhering to the placement in the SVG file. 

Example of functionality in LaserWeb can be seen here: https://plus.google.com/105504973000570609199/posts/NbrpcwhKSR5?sfc=true

SVG file here: https://www.dropbox.com/s/xo7ad5e1bdtznpp/LW-Test.svg?dl=0

Isolated example:
![svg-parser-error](https://cloud.githubusercontent.com/assets/8764001/21368348/417b3fe8-c6d0-11e6-9d7a-654452d19fd8.gif)

**Comment by tbfleming** [comment]
I'm attaching a simplified reproduction.

[simplified LW-Test.svg.txt](https://github.com/lautr3k/lw.svg-parser/files/664838/simplified.LW-Test.svg.txt)

Here's what it should look like (Inkscape):

![image](https://cloud.githubusercontent.com/assets/418464/21369181/bcbefd40-c6d3-11e6-861d-78f044e251df.png)

Here's what lw.svg-parser does:

![image](https://cloud.githubusercontent.com/assets/418464/21369213/e07e01c2-c6d3-11e6-8cd2-62ba0a32536c.png)

**Comment by ghost** [comment]
Cause: RTFM!!!

> Start a new sub-path at the given (x,y) coordinate. M (uppercase) indicates that absolute coordinates will follow; m (lowercase) indicates that relative coordinates will follow. If a moveto is followed by multiple pairs of coordinates, the subsequent pairs are treated as implicit lineto commands. Hence, implicit lineto commands will be relative if the moveto is relative, and absolute if the moveto is absolute. **If a relative moveto (m) appears as the first element of the path, then it is treated as a pair of absolute coordinates.** In this case, subsequent pairs of coordinates are treated as relative even though the initial moveto is interpreted as an absolute moveto.
